name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  MIX_ENV: test

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp: ['23.3.4', '24', '25.1']
        elixir: ['1.12.x', '1.13.x', '1.14.x']

    steps:
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get --only test

    - name: Check Formatting
      run: mix format --check-formatted
      if: matrix.check_formatted

    - name: Compiles without warnings
      run: mix compile --warnings-as-errors
      if: matrix.warnings_as_errors

    - name: Run Tests
      run: mix test
